// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: permissions.sql

package db

import (
	"context"
)

const addPermissionsForUser = `-- name: AddPermissionsForUser :exec
INSERT INTO users_permissions (user_id, permission_id)
SELECT $1, permissions.id FROM permissions WHERE permissions.code = ANY($2::text[])
`

type AddPermissionsForUserParams struct {
	UserID  int64
	Column2 []string
}

func (q *Queries) AddPermissionsForUser(ctx context.Context, arg AddPermissionsForUserParams) error {
	_, err := q.db.Exec(ctx, addPermissionsForUser, arg.UserID, arg.Column2)
	return err
}

const getPermissionsForUser = `-- name: GetPermissionsForUser :many
SELECT permissions.code
FROM permissions
INNER JOIN users_permissions ON users_permissions.permission_id = permissions.id
INNER JOIN users ON users_permissions.user_id = users.id
WHERE users.id = $1
`

func (q *Queries) GetPermissionsForUser(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.Query(ctx, getPermissionsForUser, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
